### PR TITLE
Add support for setting Network Password

### PR DESCRIPTION
**Pull request by alterbridge86**
With the release of the latest projectors (NZ series and their respective RS variants) JVC has decided to implement a "Network Password" which must be sent during the 3-way handshake in order to interact with the projector. This PR adds support for the network password to the integration. 

A pre-requisite for this to work is that the PR for the underlying python library be merged as well: https://github.com/bezmi/jvc_projector/pull/13 

**Bonus Change** 
Renamed device_state_attributes to extra_state_attributes per the latest HA guidelines: https://developers.home-assistant.io/docs/core/entity/?_highlight=extra_state_attributes#generic-properties

### CODE REVIEW

**Comment by bezmi** [comment]
Again, apologies for the delay. I will get this merged as soon as I process the release for the updated python module.

**Comment by telsin** [comment]
Any update on this merge and updating the HACS component? Looking forward to it!

**Comment by bezmi** [comment]
Thanks everyone!

**Comment by telsin** [comment]
Awesome, thanks! Can confirm it works with the RS4100/NZ9 model.

**Pull request merged**
